import "./globals.css";
import { cookies } from "next/headers";
import { Bai_Jamjuree, Roboto } from "next/font/google";
// import { Header } from "@/components/Header";
// import { Footer } from "@/components/Footer";
// import { Seasons } from "@/components/Seasons";

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-bai-jamjuree",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Meu Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const isAuthenticated = cookies().has("@meu-time:token-1.0.0");

  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.variable} ${baiJamjuree.variable} bg-neutral-900 font-sans text-neutral-100`}
      >
        {children}
      </body>
    </html>
  );
}
